[package]
name = "yt-chanvids"
version = "1.2.0"
authors = ["Daniel Araujo <contact@daniel-araujo.pt>"]

[dependencies]

# HTTP requests.
hyper = "0.13"
hyper-tls = "0.4"
futures = "0.3"
tokio = { version = "0.2", features = ["full", "blocking"] }

# Parsing command line.
getopts = "0.2"

# Parsing json, url query strings.
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_qs = "0.2"
